### ISSUE TITLE
How to implement on LLFF dataset

### ISSUE THREAD

**Issue by city19992** [mjmjeong/InfoNeRF#8]
Hi, nice job!

I am trying to use infonerf on LLFF dataset, but I fail because the program can not find the 'data_splits.pth'. And I also did not find this file in LLFF dataset.

Therefore, could you please tell me where the 'data_splits.pth' is? I would be grateful if you could teach us how to run the program on LLFF datasets.

**Comment by Jingbo-gao** [comment]
Me too, I have trapped by the same trouble.

**Comment by Jingbo-gao** [comment]
> Hi, nice job!
> 
> I am trying to use infonerf on LLFF dataset, but I fail because the program can not find the 'data_splits.pth'. And I also did not find this file in LLFF dataset.
> 
> Therefore, could you please tell me where the 'data_splits.pth' is? I would be grateful if you could teach us how to run the program on LLFF datasets.

You can delete this code, it doesn't matter.

**Comment by mjmjeong** [comment]
Please check the updated checkpoints on LLFF and DTU [here](https://drive.google.com/drive/folders/1sw1uAmSVw1K3Mw76yRCk1jD7muQH9yVS).
